version: '3.4'

services:
  mailscheduler:
    container_name: mailscheduler
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: ./Web.Api/Dockerfile
    restart: always
    environment: 
      - TZ=Australia/Melbourne

  mongo:
    container_name: mongo
    image: mongo:4.4.7
    command: [--auth]
    ports:
      - "27017:27017"
    restart: always
