version: '3.4'

services:
  mailscheduler:
    container_name: mailscheduler
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: ./Web.Api/Dockerfile
    restart: always
    environment: 
      - TZ=Australia/Melbourne

  mongo:
    container_name: mongo
    image: mongo:4.4.7
    command: [--auth]
    ports:
      - "27017:27017"
    restart: always

  mongo-express:
    image: mongo-express:0.49.0
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=blank
      - ME_CONFIG_BASICAUTH_PASSWORD=blank
      - ME_CONFIG_MONGODB_ADMINUSERNAME=blank
      - ME_CONFIG_MONGODB_ADMINPASSWORD=blank
    ports:
      - "8081:8081"
    links:
      - mongo
    restart: always
