version: '3.4'

services:
  novarmailscheduler:
    container_name: novarmailscheduler
    expose:
      - 5000
    ports:
      - "5000:80"
    build:
      context: .
      dockerfile: ./Web.Api/Dockerfile

  mongo:
    container_name: mongodb
    image: mongo:4.4.7
    command: [--auth]
    expose:
      - 27017

  mongo-express:
    image: mongo-express:0.49.0
    environment:
    - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
    - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
    - ME_CONFIG_MONGODB_ADMINPASSWORD=password
    - ME_CONFIG_BASICAUTH_USERNAME=admin
    - ME_CONFIG_BASICAUTH_PASSWORD=password
    ports:
    - "8081:8081"
    links:
      - mongo